language: node_js
node_js:
  - stable
addons:
  apt:
    packages:
      # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves for cypress
      - libgconf-2-4
branches:
  only:
    - master
script:
  - yarn lint
  - lerna run build
  - lerna run storybook:build
  - lerna run test
before_deploy:
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
  - git config --global push.default simple
  - git config --global user.email "watdevex@us.ibm.com"
  - git config --global user.name "Watson Github Bot"
  - git config remote.origin.url https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}
  - git checkout master

deploy:
  - provider: script
    script: npx lerna publish -y --create-release github
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: npx lerna publish -y --conventional-prerelease --preid beta --dist-tag beta
    skip_cleanup: true
    on:
      branch: develop
notifications:
  email:
    on_success: change
    on_failure: always
